---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: ublue-home
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/aurora
image-version: latest

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - from-file: flatpaks.yml
  - from-file: common-modules.yml
#  - from-file: bazzite.yml
  - type: rpm-ostree
    replace:
      - from-repo: https://copr.fedorainfracloud.org/coprs/danayer/linux-firmware-git/repo/fedora-41/danayer-linux-firmware-git-fedora-41.repo
        packages:
          - amd-gpu-firmware
          - amd-ucode-firmware
          - atheros-firmware
          - brcmfmac-firmware
          - cirrus-audio-firmware
          - intel-audio-firmware
          - intel-gpu-firmware
          - intel-vsc-firmware
          - iwlegacy-firmware
          - iwlwifi-dvm-firmware
          - iwlwifi-mvm-firmware
          - libertas-firmware
          - linux-firmware
          - linux-firmware-whence
          - mt7xxx-firmware
          - nvidia-gpu-firmware
          - nxpwireless-firmware
          - realtek-firmware
          - tiwilink-firmware
